# site properties and page defaults
title: SKILL Lab Lehigh University
subtitle: 
description: The STEM Knowledge Integration & Learning Lab (SKILL) at Lehigh University, led by Dr. Juan Zheng, explores innovative ways to enhance STEM education through technology. The lab focuses on understanding how emotional, motivational, and cognitive factors shape self-regulated learning, developing AI-powered simulations, and promoting K-12 students’ AI literacy through hands-on problem-solving. By combining advanced research methods like multimodal data analysis, the SKILL lab creates and evaluates cutting-edge tools to help students integrate STEM knowledge and apply it in real-world contexts.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@SKILL-Lab-Lehigh.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: SKILL-Lab-Lehigh
  twitter: SKILL-Lab-Lehigh

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
